server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=load_balanced_route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://example-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/loadbalanced/**

resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50